// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABIr_CgXmqWSavTNMr-CEGO7Mux9yKYXU',
    appId: '1:1084371519631:web:4d54d3837fffd65e8048fa',
    messagingSenderId: '1084371519631',
    projectId: 'expensetracker-c97ca',
    authDomain: 'expensetracker-c97ca.firebaseapp.com',
    storageBucket: 'expensetracker-c97ca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAskiJZy8uwvv_ys2sXOC-KwtxZKTL8R88',
    appId: '1:1084371519631:android:1c205d8955f7c7958048fa',
    messagingSenderId: '1084371519631',
    projectId: 'expensetracker-c97ca',
    storageBucket: 'expensetracker-c97ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmmhV6lbpVzAiU3dlOtJWpT224A-OxPuA',
    appId: '1:1084371519631:ios:235b9efe106b2aa48048fa',
    messagingSenderId: '1084371519631',
    projectId: 'expensetracker-c97ca',
    storageBucket: 'expensetracker-c97ca.appspot.com',
    iosBundleId: 'com.example.expensetracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmmhV6lbpVzAiU3dlOtJWpT224A-OxPuA',
    appId: '1:1084371519631:ios:7e170ce4a77b77a48048fa',
    messagingSenderId: '1084371519631',
    projectId: 'expensetracker-c97ca',
    storageBucket: 'expensetracker-c97ca.appspot.com',
    iosBundleId: 'com.example.expensetracker.RunnerTests',
  );
}
